# ==============================================================================
# WEB ADMIN LOGIN & DASHBOARD ELEMENT REPOSITORY
# ==============================================================================
admin.login.email=//input[@placeholder='Enter your email']
admin.login.password=//input[@placeholder='Enter your password']
admin.login.submit_btn=//button[@type='submit']
admin.dashboard.statistics_header=//div[contains(text(),'Date Wise Statistics')]